version: '3.8'

services:
  fmerids-app:
    build: ./backend
    container_name: fmerids-prod
    restart: always
    ports:
      - "80:5001"
    volumes:
      - fmerids-data:/app/data
    environment:
      - FLASK_ENV=production

volumes:
  fmerids-data:

